name: SimpleEconomyUI
version: 0.0.1
main: RicardoMilos384\SimpleEconomyUI\Main
api: 3.11.0
website: https://github.com/RicardoMilos384/SimpleEconomyUI
description: EconomyUI plugin to manage your money easier
authors: ["DontTouchMeXD", "DavyCraft648"]
depend: EconomyAPI
commands:
  economyui:
    description: Open EconomyUI menu
    aliases:
      - ecoui