name: SimpleEconomyUI
version: 1.0.0
main: EcoUI\Main
api: 3.9.3
author: DontTouchMeXD
description: EconomyUI plugin to make your life easy (please dont edit and claim this plugin)
commands:
 ecoui:
  description: "§aopen economyUI menu"
  aliases: [economyui, econui, ecui]
